// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = IntroSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Member documents */
interface MemberDocumentData {
    /**
     * Slice Zone field in *Member*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: member.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MemberDocumentDataSlicesSlice>;
}
/**
 * Slice for *Member → Slice Zone*
 *
 */
type MemberDocumentDataSlicesSlice = MemberDetailSlice;
/**
 * Member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<MemberDocumentData>, "member", Lang>;
export type AllDocumentTypes = HomepageDocument | MemberDocument;
/**
 * Primary content in Intro → Primary
 *
 */
interface IntroSliceDefaultPrimary {
    /**
     * Title field in *Intro → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: intro.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Intro → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: intro.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Intro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<IntroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Intro*
 *
 */
type IntroSliceVariation = IntroSliceDefault;
/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: `Intro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSlice = prismicT.SharedSlice<"intro", IntroSliceVariation>;
/**
 * Primary content in MemberCard → Primary
 *
 */
interface MemberDetailSliceDefaultPrimary {
    /**
     * Member Name field in *MemberCard → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member_detail.primary.member_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    member_name: prismicT.RichTextField;
    /**
     * Short Description field in *MemberCard → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member_detail.primary.short_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    short_description: prismicT.RichTextField;
    /**
     * Profile Picture field in *MemberCard → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: member_detail.primary.profile_picture
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_picture: prismicT.ImageField<never>;
}
/**
 * Default variation for MemberCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MemberDetail`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MemberDetailSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MemberDetailSliceDefaultPrimary>, never>;
/**
 * Slice variation for *MemberCard*
 *
 */
type MemberDetailSliceVariation = MemberDetailSliceDefault;
/**
 * MemberCard Shared Slice
 *
 * - **API ID**: `member_detail`
 * - **Description**: `MemberDetail`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MemberDetailSlice = prismicT.SharedSlice<"member_detail", MemberDetailSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, MemberDocumentData, MemberDocumentDataSlicesSlice, MemberDocument, AllDocumentTypes, IntroSliceDefaultPrimary, IntroSliceDefault, IntroSliceVariation, IntroSlice, MemberDetailSliceDefaultPrimary, MemberDetailSliceDefault, MemberDetailSliceVariation, MemberDetailSlice };
    }
}
