// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from '@prismicio/types';
import type * as prismic from '@prismicio/client';

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = IntroSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
>;
export type AllDocumentTypes = HomepageDocument;
/**
 * Primary content in Intro → Primary
 *
 */
interface IntroSliceDefaultPrimary {
    /**
     * Title field in *Intro → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: intro.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Intro → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: intro.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Intro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSliceDefault = prismicT.SharedSliceVariation<'default', Simplify<IntroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Intro*
 *
 */
type IntroSliceVariation = IntroSliceDefault;
/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: `Intro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSlice = prismicT.SharedSlice<'intro', IntroSliceVariation>;
declare module '@prismicio/client' {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type {
            HomepageDocumentData,
            HomepageDocumentDataSlicesSlice,
            HomepageDocument,
            AllDocumentTypes,
            IntroSliceDefaultPrimary,
            IntroSliceDefault,
            IntroSliceVariation,
            IntroSlice,
        };
    }
}
