// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Community Team Top Title documents */
interface CommunityTeamTopTitleDocumentData {
    /**
     * Title field in *Community Team Top Title*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: community_team_top_title.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Community Team Top Title*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: community_team_top_title.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Community Team Top Title document from Prismic
 *
 * - **API ID**: `community_team_top_title`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CommunityTeamTopTitleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CommunityTeamTopTitleDocumentData>, "community_team_top_title", Lang>;
/** Content for Contact Header Image documents */
interface ContactHeaderImageDocumentData {
    /**
     * Image field in *Contact Header Image*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_header_image.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Contact Header Image document from Prismic
 *
 * - **API ID**: `contact_header_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactHeaderImageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ContactHeaderImageDocumentData>, "contact_header_image", Lang>;
/** Content for Event documents */
interface EventDocumentData {
    /**
     * Title field in *Event*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Venue field in *Event*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.venue
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    venue: prismicT.KeyTextField;
    /**
     * Image field in *Event*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: event.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Price field in *Event*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: event.price
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    price: prismicT.NumberField;
    /**
     * Start date field in *Event*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: event.start_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    start_date: prismicT.TimestampField;
    /**
     * End date field in *Event*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: event.end_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    end_date: prismicT.TimestampField;
    /**
     * Registration link field in *Event*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: event.registration_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    registration_link: prismicT.LinkField;
    /**
     * Description field in *Event*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: event.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Speakers field in *Event*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: event.speakers[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    speakers: prismicT.GroupField<Simplify<EventDocumentDataSpeakersItem>>;
}
/**
 * Item in Event → Speakers
 *
 */
export interface EventDocumentDataSpeakersItem {
    /**
     * Speaker field in *Event → Speakers*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: event.speakers[].speaker
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    speaker: prismicT.LinkField;
}
/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;
/** Content for Events Header Image documents */
interface EventsHeaderImageDocumentData {
    /**
     * Image field in *Events Header Image*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: events_header_image.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Events Header Image document from Prismic
 *
 * - **API ID**: `events_header_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsHeaderImageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<EventsHeaderImageDocumentData>, "events_header_image", Lang>;
/** Content for Footer Column Center documents */
interface FooterColumnCenterDocumentData {
    /**
     * Title field in *Footer Column Center*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_center.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Items field in *Footer Column Center*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_center.items[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    items: prismicT.GroupField<Simplify<FooterColumnCenterDocumentDataItemsItem>>;
}
/**
 * Item in Footer Column Center → Items
 *
 */
export interface FooterColumnCenterDocumentDataItemsItem {
    /**
     * Item field in *Footer Column Center → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_center.items[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item: prismicT.RichTextField;
}
/**
 * Footer Column Center document from Prismic
 *
 * - **API ID**: `footer_column_center`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterColumnCenterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterColumnCenterDocumentData>, "footer_column_center", Lang>;
/** Content for Footer Column Left documents */
interface FooterColumnLeftDocumentData {
    /**
     * Title field in *Footer Column Left*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_left.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Items field in *Footer Column Left*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_left.items[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    items: prismicT.GroupField<Simplify<FooterColumnLeftDocumentDataItemsItem>>;
}
/**
 * Item in Footer Column Left → Items
 *
 */
export interface FooterColumnLeftDocumentDataItemsItem {
    /**
     * Item field in *Footer Column Left → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_left.items[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item: prismicT.RichTextField;
}
/**
 * Footer Column Left document from Prismic
 *
 * - **API ID**: `footer_column_left`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterColumnLeftDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterColumnLeftDocumentData>, "footer_column_left", Lang>;
/** Content for Footer Column Right documents */
interface FooterColumnRightDocumentData {
    /**
     * Title field in *Footer Column Right*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_right.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Items field in *Footer Column Right*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_right.items[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    items: prismicT.GroupField<Simplify<FooterColumnRightDocumentDataItemsItem>>;
}
/**
 * Item in Footer Column Right → Items
 *
 */
export interface FooterColumnRightDocumentDataItemsItem {
    /**
     * Item field in *Footer Column Right → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_column_right.items[].item
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item: prismicT.RichTextField;
}
/**
 * Footer Column Right document from Prismic
 *
 * - **API ID**: `footer_column_right`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterColumnRightDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterColumnRightDocumentData>, "footer_column_right", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Left column field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    left_column: prismicT.GroupField<Simplify<FooterDocumentDataLeftColumnItem>>;
    /**
     * Center column field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    center_column: prismicT.GroupField<Simplify<FooterDocumentDataCenterColumnItem>>;
    /**
     * Right Column field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    right_column: prismicT.GroupField<Simplify<FooterDocumentDataRightColumnItem>>;
}
/**
 * Item in Footer → Left column
 *
 */
export interface FooterDocumentDataLeftColumnItem {
    /**
     * Title field in *Footer → Left column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Link1 Label field in *Footer → Left column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].link1_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link1_label: prismicT.RichTextField;
    /**
     * Link1 field in *Footer → Left column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].link1
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link1: prismicT.LinkField;
    /**
     * Link2 Label field in *Footer → Left column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].link2_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link2_label: prismicT.RichTextField;
    /**
     * Link2 field in *Footer → Left column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].link2
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link2: prismicT.LinkField;
    /**
     * Link3 Label field in *Footer → Left column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].link3_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link3_label: prismicT.RichTextField;
    /**
     * Link3 field in *Footer → Left column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.left_column[].link3
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link3: prismicT.LinkField;
}
/**
 * Item in Footer → Center column
 *
 */
export interface FooterDocumentDataCenterColumnItem {
    /**
     * Title field in *Footer → Center column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Link1 Label field in *Footer → Center column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link1_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link1_label: prismicT.RichTextField;
    /**
     * Link1 field in *Footer → Center column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link1
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link1: prismicT.LinkField;
    /**
     * Link2 Label field in *Footer → Center column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link2_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link2_label: prismicT.RichTextField;
    /**
     * Link2 field in *Footer → Center column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link2
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link2: prismicT.LinkField;
    /**
     * Link3 Label field in *Footer → Center column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link3_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link3_label: prismicT.RichTextField;
    /**
     * Link3 field in *Footer → Center column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link3
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link3: prismicT.LinkField;
    /**
     * Link4 Label field in *Footer → Center column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link4_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link4_label: prismicT.RichTextField;
    /**
     * Link4 field in *Footer → Center column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link4
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link4: prismicT.LinkField;
    /**
     * Link5 Label field in *Footer → Center column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link5_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link5_label: prismicT.RichTextField;
    /**
     * Link5 field in *Footer → Center column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.center_column[].link5
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link5: prismicT.LinkField;
}
/**
 * Item in Footer → Right Column
 *
 */
export interface FooterDocumentDataRightColumnItem {
    /**
     * Title field in *Footer → Right Column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Link1 Label field in *Footer → Right Column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link1_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link1_label: prismicT.RichTextField;
    /**
     * Link1 field in *Footer → Right Column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link1
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link1: prismicT.LinkField;
    /**
     * Link2 Label field in *Footer → Right Column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link2_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link2_label: prismicT.RichTextField;
    /**
     * Link2 field in *Footer → Right Column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link2
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link2: prismicT.LinkField;
    /**
     * Link3 Label field in *Footer → Right Column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link3_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link3_label: prismicT.RichTextField;
    /**
     * Link3 field in *Footer → Right Column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link3
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link3: prismicT.LinkField;
    /**
     * Link4 Label field in *Footer → Right Column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link4_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link4_label: prismicT.RichTextField;
    /**
     * Link4 field in *Footer → Right Column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link4
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link4: prismicT.LinkField;
    /**
     * Link5 Label field in *Footer → Right Column*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link5_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link5_label: prismicT.RichTextField;
    /**
     * Link5 field in *Footer → Right Column*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.right_column[].link5
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link5: prismicT.LinkField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage Attribute documents */
interface HomepageAttributeDocumentData {
    /**
     * Title field in *Homepage Attribute*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage_attribute.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Homepage Attribute*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage_attribute.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Homepage Attribute document from Prismic
 *
 * - **API ID**: `homepage_attribute`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageAttributeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageAttributeDocumentData>, "homepage_attribute", Lang>;
/** Content for Homepage Events Header documents */
interface HomepageEventsHeaderDocumentData {
    /**
     * Title field in *Homepage Events Header*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage_events_header.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Homepage Events Header*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage_events_header.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Homepage Events Header document from Prismic
 *
 * - **API ID**: `homepage_events_header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageEventsHeaderDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageEventsHeaderDocumentData>, "homepage_events_header", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Homepage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = IntroSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Member documents */
interface MemberDocumentData {
    /**
     * Name field in *Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Motto field in *Member*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member.motto
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    motto: prismicT.RichTextField;
    /**
     * Profile photo field in *Member*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: member.profile_photo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_photo: prismicT.ImageField<never>;
    /**
     * Phone number field in *Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member.phone_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number: prismicT.KeyTextField;
    /**
     * Email field in *Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Webpage field in *Member*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: member.webpage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    webpage: prismicT.LinkField;
    /**
     * Description field in *Member*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: member.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<MemberDocumentData>, "member", Lang>;
/** Content for Members Top Banner documents */
interface MembersTopBannerDocumentData {
    /**
     * Image field in *Members Top Banner*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: members_top_banner.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Description field in *Members Top Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: members_top_banner.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Members Top Banner document from Prismic
 *
 * - **API ID**: `members_top_banner`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MembersTopBannerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MembersTopBannerDocumentData>, "members_top_banner", Lang>;
/** Content for Members Top Title documents */
interface MembersTopTitleDocumentData {
    /**
     * Title field in *Members Top Title*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: members_top_title.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Members Top Title*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: members_top_title.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Members Top Title document from Prismic
 *
 * - **API ID**: `members_top_title`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MembersTopTitleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MembersTopTitleDocumentData>, "members_top_title", Lang>;
/** Content for News Header Image documents */
interface NewsHeaderImageDocumentData {
    /**
     * Image field in *News Header Image*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: news_header_image.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * News Header Image document from Prismic
 *
 * - **API ID**: `news_header_image`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsHeaderImageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NewsHeaderImageDocumentData>, "news_header_image", Lang>;
/** Content for News documents */
interface NewsDocumentData {
    /**
     * Title field in *News*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: news.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *News*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: news.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *News*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: news.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;
/** Content for Speaker documents */
interface SpeakerDocumentData {
    /**
     * Name field in *Speaker*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Info field in *Speaker*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.info
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    info: prismicT.RichTextField;
    /**
     * Image field in *Speaker*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Short info field in *Speaker*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: speaker.short_info
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    short_info: prismicT.RichTextField;
}
/**
 * Speaker document from Prismic
 *
 * - **API ID**: `speaker`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpeakerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SpeakerDocumentData>, "speaker", Lang>;
export type AllDocumentTypes = CommunityTeamTopTitleDocument | ContactHeaderImageDocument | EventDocument | EventsHeaderImageDocument | FooterColumnCenterDocument | FooterColumnLeftDocument | FooterColumnRightDocument | FooterDocument | HomepageAttributeDocument | HomepageEventsHeaderDocument | HomepageDocument | MemberDocument | MembersTopBannerDocument | MembersTopTitleDocument | NewsHeaderImageDocument | NewsDocument | SpeakerDocument;
/**
 * Primary content in Intro → Primary
 *
 */
interface IntroSliceDefaultPrimary {
    /**
     * Title field in *Intro → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: intro.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Intro → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: intro.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Intro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<IntroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Intro*
 *
 */
type IntroSliceVariation = IntroSliceDefault;
/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: `Intro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSlice = prismicT.SharedSlice<"intro", IntroSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CommunityTeamTopTitleDocumentData, CommunityTeamTopTitleDocument, ContactHeaderImageDocumentData, ContactHeaderImageDocument, EventDocumentData, EventDocumentDataSpeakersItem, EventDocument, EventsHeaderImageDocumentData, EventsHeaderImageDocument, FooterColumnCenterDocumentData, FooterColumnCenterDocumentDataItemsItem, FooterColumnCenterDocument, FooterColumnLeftDocumentData, FooterColumnLeftDocumentDataItemsItem, FooterColumnLeftDocument, FooterColumnRightDocumentData, FooterColumnRightDocumentDataItemsItem, FooterColumnRightDocument, FooterDocumentData, FooterDocumentDataLeftColumnItem, FooterDocumentDataCenterColumnItem, FooterDocumentDataRightColumnItem, FooterDocument, HomepageAttributeDocumentData, HomepageAttributeDocument, HomepageEventsHeaderDocumentData, HomepageEventsHeaderDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, MemberDocumentData, MemberDocument, MembersTopBannerDocumentData, MembersTopBannerDocument, MembersTopTitleDocumentData, MembersTopTitleDocument, NewsHeaderImageDocumentData, NewsHeaderImageDocument, NewsDocumentData, NewsDocument, SpeakerDocumentData, SpeakerDocument, AllDocumentTypes, IntroSliceDefaultPrimary, IntroSliceDefault, IntroSliceVariation, IntroSlice };
    }
}
