// Code generated by Slice Machine. DO NOT EDIT.

import Intro from './Intro';
import MemberCard from './MemberCard';

export {
	Intro,
	MemberCard,
};

export const components = {
	intro: Intro,
	member_detail: MemberCard,
};
